version: '3.8'

services:
  forum:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./volume/database:/app/volume/database
      - ./volume/uploaded_imgs:/app/volume/uploaded_imgs
    restart: unless-stopped
